---
docker:
  image: yegor256/java

architect: RoRoche

install: |
  mvn -version

merge:
  script:
    - mvn clean install -DskipTests
  squash: false
  rebase: true

release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}" -Dstyle.color=never
    npm version "${tag}" --no-git-tag-version
    git commit -am ":bookmark: ${tag}"
    mvn -B -P release clean deploy
