---
docker:
  image: yegor256/java
assets:
  settings.xml: roroche/home#assets/eoconfig/settings.xml
  pubring.gpg: roroche/home#assets/pubring.gpg
  secring.gpg: roroche/home#assets/secring.gpg
architect: RoRoche
install: |
  mvn -version
merge:
  script:
    - mvn clean install -DskipTests
  squash: false
  rebase: true
release:
  sensitive:
    - settings.xml
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    cp /home/r/assets/roroche/home/assets/eoconfig/settings.xml ./settings.xml
    gpg --import /home/r/assets/roroche/home/assets/eoconfig/secring.gpg
    gpg --import /home/r/assets/roroche/home/assets/eoconfig/pubring.gpg
    echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
    echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
    gpgconf --kill gpg-agent
    mvn versions:set "-DnewVersion=${tag}" -Dstyle.color=never
    git commit -am ":bookmark: ${tag}"
    mvn -B -P release,ossrh --settings settings.xml clean deploy
    git tag -a "${tag}" -m "Release ${tag}"
    git push origin "${tag}"
